// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tAL8OzZ5P6lf2R_SEKZM9DddZnnHuVM',
    appId: '1:487409198060:web:5f354abf60bad6bf6416c9',
    messagingSenderId: '487409198060',
    projectId: 'room-genius',
    authDomain: 'room-genius.firebaseapp.com',
    storageBucket: 'room-genius.firebasestorage.app',
    measurementId: 'G-ZMFTY46FS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh04kfjqo1WBMBjJdva1Sr_6yuoMX0mp0',
    appId: '1:487409198060:android:4835fc64e240fa8f6416c9',
    messagingSenderId: '487409198060',
    projectId: 'room-genius',
    storageBucket: 'room-genius.firebasestorage.app',
  );
}
